   # Numpy Examples 

In [1]:
#  numpy example

In [6]:
import numpy as np 
x= np.array([1, 2, 3])
print(x[0])
# print('\n')

print(x[1])

print(x[2])

# print(x[5]) : index error, out of bounds for axis 0

1
2
3


In [3]:
a= np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
x= np.array([[1, 2, 3], [4, 5, 6]])

print(type(x))

<class 'numpy.ndarray'>


In [7]:
x= np.array([[1, 2, 3], [4,5, 6], [7, 8, 9]])
print(x[1])
print(x[2])

[4 5 6]
[7 8 9]


In [8]:
import pandas as pd
import numpy as np 
import matplotlib as plt

a1= np.array([3])
a2 = np.array([4])
print(a1+a2)

[7]


In [9]:
a3= np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
print(a3+a4)

[5 7 9]


In [10]:
a3= np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
print(a3-a4)

[-3 -3 -3]


In [11]:
a3= np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
print(a3*a4)

[ 4 10 18]


In [13]:
# to convert int to float

myarr = np.array([1, 2, 3], float)
myarr

array([1., 2., 3.])

In [16]:
arr1 = np.array([[1,2,3],[4, 5, 6]])
arr1

# print(type(arr1))   #  <class 'numpy.ndarray'>

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# numpy array size (2*3) with zeros 
arr2 =np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# numpy dimensions of (3*3) with one's 
arr3 = np.ones((3, 3), int)
arr3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
arr_ones = np.ones((4, 4), float)
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# np.identity(n) function creates an n x n identity matrix — a square matrix with 1's on the main diagonal and 0's elsewhere
arr4 = np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
arr01 = np.full((3, 4), 5)    #  3 rows, 4 columns member element is 5
arr01

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
# np.full() : it will creates a new array of specified type, filled with specified values.
# np.full(shape, fill_value, dtype=None, order='C'), order (optional): memory layout, 'C' for row-major, 'F' for column-major.

np_full = np.full((3, 3), 3.14, float)   #  3 * 3 scaler = 3.14, dtype= float
print(np_full)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [47]:
# same as for range in python
# np.arange([start, ]stop, [step, ]dtype=None)

arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr6 = np.arange(5, 16, 2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [49]:
# to introduce an float type 

np_arange = np.arange(1, 30, 3, dtype= float)
print(np_arange)

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


In [50]:
# linespace between the given no's 10-20, each having the same distance (11.1111111-10.0000000)
#  to create evenly spaced numbers over a specified interval.
#  np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

arr7 = np.linspace(10, 20, 10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [51]:
#  This creates 5 numbers evenly spaced between 0 and 1 (including both ends).
lspace = np.linspace(0, 1, 5)
print(lspace)

[0.   0.25 0.5  0.75 1.  ]


In [52]:
arr, step = np.linspace(0, 1, 5, retstep=True)
print("Array:", arr)
print("Step size:", step)

Array: [0.   0.25 0.5  0.75 1.  ]
Step size: 0.25


In [53]:
# to copy any numpy arrays
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [54]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

# Numpy Properties &  Attributes 

In [55]:
# shape of the matrix dimension
arr2.shape

(2, 3)

In [56]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [57]:
arr7.shape

(10,)

In [58]:
arr9 = np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [59]:
#  NumPy array has a shape of (2, 2, 2), it means the array is 3-dimensional with these dimensions:
#  a "cube" or a stack of 2 matrices, where: There are 2 blocks, Each block is a 2x2 matrix.

arr9.shape

(2, 2, 2)

In [63]:
# 3 dimensional matrix 
arr9.ndim

3

In [64]:
arr9[0]

array([[1, 2],
       [3, 4]])

In [65]:
arr9[1]

array([[5, 6],
       [7, 8]])

In [66]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
# 2 dim matrix 
arr2.ndim

2

In [69]:
# size : Number of elements in the array.
arr2.size

6

In [70]:
arr9.size

8

In [71]:
# itemsize : Length of one array element in bytes.
# itemsize is an attribute of an array that tells you the size (in bytes) of each element in the array.

arr2.itemsize

8

In [72]:
arr9.itemsize

8

In [76]:
# dtype: data type of the elemenst
arr2.dtype

dtype('float64')

In [77]:
arr9.dtype

dtype('int64')

In [78]:
# conversion of data types
arr2.astype('float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
print(arr2.dtype)

float64


#  Dimensions in numpy  

In [85]:
# 0 - d array: A dimension in arrays is one level of array depth (nested arrays).

import numpy as np

arr10 = np.array(42)
print(arr10)

42


In [86]:
# 1 -D array

import numpy as np

arr11 = np.array([1, 2, 3, 5, 8, 9])
print(arr11)

[1 2 3 5 8 9]


In [87]:
#  2 - D array, Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
import numpy as np

arr12 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr12)

print(type(arr12))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [88]:
# 3 - D array, An array that has 2-D arrays (matrices) as its elements is called 3-D array. 
import numpy as np

arr13 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr13)

print("\n")

print(type(arr13))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<class 'numpy.ndarray'>


In [92]:
# 2 blocks each having the 2 rows and 3 columns 
arr13.shape

(2, 2, 3)

In [93]:
# n-dim matrix

arr13.ndim

3

In [94]:
# to check the number of dimensions, ndim attribute that returns an integer that tells us how many dimensions the array have.

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [95]:
# Higher Dimensional Arrays, to define the number of dimensions by using the ndmin argument

import numpy as np

arr14 = np.array([1, 2, 3, 4], ndmin = 5)

print(arr14)

print("\n")
print("To print the dimensions of the array: ", arr14.ndim)

[[[[[1 2 3 4]]]]]


To print the dimensions of the array:  5


# To identify the dimension of the array

Each pair of brackets adds a dimension:

1). 1 2 3 4 — this is a 1D array with 4 elements. Wrapping it in one set of brackets: [[1 2 3 4]] → shape (1, 4)
2). Another bracket: [[[1 2 3 4]]] → shape (1, 1, 4)
3). Another: [[[[1 2 3 4]]]] → shape (1, 1, 1, 4)
4). And one more: [[[[[1 2 3 4]]]]] → shape (1, 1, 1, 1, 4)

In [99]:
# Numpy arraay Indexing, same as accessing array. access an array element by referring to its index number(starts with 0,1..)

# to access the second array elements, arr[0] : as the first element 

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1]) 

2


In [100]:
# to add the 2 & 3rd elements

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) 

7


In [101]:
# To access the  2-D arrays, 
# 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print("\n")

# expect 5
print('4th element on 1st row: ', arr[0, 4])
print("\n")

# expect 8
print('2nd element on 2nd row: ', arr[1, 2])
print("\n")

# expect 10 
print('4th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2


4th element on 1st row:  5


2nd element on 2nd row:  8


4th element on 2nd row:  10


In [50]:
# Access the 3-D arrays, use comma separated integers representing the dimensions and the index of the element

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


Example Explained: arr[0, 1, 2] prints the value 6.

And this is why:
The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]  and:  [[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]  and: [4, 5, 6]
Since we selected 1, we are left with the second array: [4, 5, 6]

The third number represents the third dimension, which contains three values: 4 5 6 
Since we selected 2, we end up with the third value: 6

In [102]:
#  Numpy array slicing, result includes the start index, but excludes the end index (start, end, steps)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 


[2 4]


In [103]:
# Use the minus operator to refer to an index from the end(-1, also end not included. -3, means start and -1 end, but -1 excluded)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


In [104]:
# Slicing 2 - D arrays, From the second element, slice elements from index 1 to index 4 (not included):
# 2-D arrays, 0 & 1, so it picked 2nd array(6-10) and slicing the elements from 1-4, but 4 excluded.

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr.ndim

print("\n")

print(arr[1, 1:4]) 



[7 8 9]


In [61]:
# from both the elements, returns index 2 (0-2, arrays, and choosed the 2nd elements from each arrays)
# arr[0:2, 2] means: 0:2 selects rows 0 and 1 (since the end index 2 is exclusive), 2 selects the element at column index 2

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) 

[3 8]


In [106]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# print(arr[0:1, 1:4])     # select only from 1st rows and then elements from 1 to 4(exclusive)

print(arr[0:2, 1:4])       # both rows 0 and 1(inclusive), and then 1:4 index positions elements(exclusive)

[[2 3 4]
 [7 8 9]]


Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


**String (S dtype)
Represented as numpy.string_ or dtype starting with 'S'. Stores byte strings (8-bit ASCII or raw bytes).
Fixed-length byte sequences. Mainly for ASCII or binary data.

Example dtype: S10 — string of max length 10 bytes. Does not support Unicode characters beyond ASCII.

2. Unicode String (U dtype)
Represented as numpy.unicode_ or dtype starting with 'U'. Stores Unicode characters using 4 bytes per character internally (UTF-32).
Fixed-length Unicode strings. Supports all Unicode characters (e.g., emoji, accented letters, non-Latin scripts).

Example dtype: U10 — Unicode string of max length 10 characters.

Important notes:
When working with text data involving non-ASCII characters, use Unicode (U).
Byte strings (S) are mostly legacy or for raw byte data.
Unicode strings consume more memory (4 bytes per char).

In [63]:
#  dtype: NumPy array object has a property called dtype that returns the data type of the array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype) 

int32


In [64]:
# string type

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 

<U6


In [107]:
arrt = np.array(["Apple", "Banana", "Cherry", "Mango", "Orange"])

print(arrt.dtype)

<U6


In [109]:
# defined data type
#  dtype='S' means: store elements as byte strings. The array is given Python integers [1, 2, 3, 4].
#  NumPy will convert each integer to its byte string representation. For integers, NumPy converts them to strings of their digits, 
#  then encodes as bytes.

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [110]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [112]:
#  If a type is given in which elements can't be casted then NumPy will raise a ValueError.

# ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
# to create an integer ('i') array from the strings 'a', '2', and '3'. '2' and '3' can be converted to integers 2 and 3.
#  But 'a' cannot be converted to an integer — it's not a valid numeric string.

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i') 


ValueError: invalid literal for int() with base 10: 'a'

In [113]:
#  Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [114]:
#  Change data type from integer to boolean:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


* NumPy Array Copy vs View

**The Difference Between Copy and View

**The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [115]:
# Make a copy, change the original array, and display both arrays, copy should not affected the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [116]:
#  Make a view, change the original array, and display both arrays, view SHOULD be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


* Numpy reshaaping arrays

**Reshaping arrays :
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [117]:
# Reshaping the arraay from 1-D to 3-D 
# Convert the following 1-D array with 12 elements into a 3-D array.
#  The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [118]:
#  Iterate on the elements of the following 2-D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [119]:
#Joining numpy arrays : a sequence of arrays that we want to join to the concatenate() function, along with the axis. 
# If axis is not explicitly passed, it is taken as 0.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [122]:
# concatenate columns wise 

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
final_arr = np.concatenate((arr_1.reshape(-1, 1), arr_2.reshape(-1, 1)), axis=1)
print(final_arr)

[[1 4]
 [2 5]
 [3 6]]


In [123]:
#  Join two 2-D arrays along rows (axis=1):
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

[[1 2 5 6]
 [3 4 7 8]]


In [125]:
# Split the array in 3 parts:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [126]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr1 = np.array_split(arr, 3)

print(newarr1) 

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [128]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [129]:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


In [130]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [131]:
# refer to the named index:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


# Lists ~ Arrays

1. Faster
2. Convenient
3. Less Memory

In [132]:
import sys
import numpy as np 

lista = range(100)
arr15 = np.arange(100)

print("For list:", sys.getsizeof(87)*len(lista))

print("\n")
print("For Array:", arr15.size* arr15.itemsize)

For list: 2800


For Array: 800


In [133]:
#  for execution time

import time
import numpy as np

x = range(1000000)
y = range(1000000, 2000000)

start_time = time.time()

c = [(x, y) for x, y in zip(x, y)]
print(time.time() - start_time)

# for numpy arrays

print("\n")
s = np.arange(1000000)
t = np.arange(1000000, 2000000)

start_time = time.time()
z = s + t
print("execution Time for Numpy:", time.time()- start_time)

0.9237115383148193


execution Time for Numpy: 0.017699003219604492


In [135]:
arr16 = np.arange(24).reshape(6, 4)
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [136]:
# slicing 
arr16[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
arr16[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [139]:
# to find last 4 elements (18, 19, 22, 23)

arr16[4:6 , 2:4]

array([[18, 19],
       [22, 23]])

In [140]:
arr16[4: , 2:]

array([[18, 19],
       [22, 23]])

In [141]:
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [142]:
for i in np.nditer(arr16):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [146]:
print(arr16.mean())


11.5


In [147]:
arr16.max()

np.int64(23)

In [148]:
arr16.min()

np.int64(0)

In [156]:
# min of each columns

arr16.min(axis=0)

array([0, 1, 2, 3])

In [157]:
arr16.max(axis=0)

array([20, 21, 22, 23])

In [158]:
# min of each rows
arr16.min(axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [159]:
arr16.max(axis=1)

array([ 3,  7, 11, 15, 19, 23])

In [154]:
# column wise sum 
arr16.sum(axis=0)

array([60, 66, 72, 78])

In [160]:
arr16.std()

np.float64(6.922186552431729)

In [161]:
np.median(arr16)

np.float64(11.5)

In [162]:
np.sin(arr16)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [163]:
np.exp(arr16)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

# Reshaping the numpy arrays 

1. Ravel
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [173]:
# pip install jupyterlab-lsp
# !pip install python-lsp-server
#!jupyter labextension install @krassowski/jupyterlab-lsp

(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 
C:\Users\psjsi\DataSC_2023\envs\Lib\site-packages\jupyterlab\debuglog.py:54: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
C:\Users\psjsi\DataSC_2023\envs\Lib\site-packages\jupyterlab\debuglog.py:55: UserWarning: ValueError: Please install nodejs >=20.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
  warnings.warn(msg[-1].strip())
C:\Users\psjsi\DataSC_2023\envs\Lib\site-packages\jupyterlab\debuglog.py:56: UserWarning: See the log file for details: C:\Users\psjsi\AppData\Local\Temp\jupyterlab-debug-mo80p0up.log
  warnings.warn(f"See the log file for details: {log_path!s}")
